### ISSUE TITLE
JSRocks rebranding

### ISSUE THREAD

**Issue by jaydson** [JSRocksHQ/jsrockshq.github.io#57]
Things to do before merging:
- [x] @robsongajunior must to confirm if the PR is ok, with the latest resources (posts, etc) updated  
We just need to use Harmonic beta (external themes support) and change the `template` property on `harmonic.json`
- [x] @jaydson and @UltCombo must test this branch  
This is not necessary anymore
- [x] We need to rename the org to `jsrocks`
- [x] Change the repository name to jsrocks.github.io
- [ ] Update the header and all references to ES6 Rocks in README and CONTRIBUTING files
- [x] Update all references to ES6 Rocks in the harmonic-theme-jsrocks
- [x] Migrate es6rocks.com to jsrocks.org (i don't know yet the best approach here)
- [x] Update CNAME to jsrocks.org
- [x] Change es6rocks Twitter account name to `jsrocks`

Anything else i have missed?

**Comment by UltCombo** [comment]
> Migrate es6rocks.com to jsrocks.org (i don't know yet the best approach here)

Perhaps make both domains point to the same IP for the time being?

**Comment by UltCombo** [comment]
Oh wait, we are using GitHub pages so it might be a bit more complicated.

**Comment by UltCombo** [comment]
We need a new slogan/description as well. The current one reads:

> ES6Rocks.com is a collaborative website about the ECMAScript language's sixth edition, a.k.a. ES6.

Perhaps we could use:

> JSRocks.org is a collaborative website about the latest JavaScript features and tools.

Or more broadly:

> JSRocks.org is a collaborative website about the JavaScript world.

**Comment by robsongajunior** [comment]
> JSRocks.org is a collaborative website about the JavaScript world.

I like.
Can I write this description in the next PR to [harmonic-theme-jsrocks](https://github.com/es6rocks/harmonic-theme-jsrocks)?

@jaydson?
