### ISSUE TITLE
Minify css and compress images?

### ISSUE THREAD

**Issue by ftonato** [JSRocksHQ/jsrockshq.github.io#61]
**CSS** using [csscompressor](http://csscompressor.com)

| Input | Output | You save | URL |
| --- | --- | --- | --- |
| 2781 bytes | 1715 bytes | 62.16% | [responsive.css](http://jsrocks.org/css/responsive.css) |
| 20716 bytes | 13904 bytes | 48.99% | [animations.css](http://jsrocks.org/css/animations.css) |

**Images** using [compressor.io](https://compressor.io/)

| Input | Output | You save | URL |
| --- | --- | --- | --- |
| 76.35 KB | 48.37 KB | 37% | [bg-header-2.jpg](http://jsrocks.org/images/bg-header-2.jpg) |
| 34.78 KB | 9.87 KB | 72% | [thumb.png](http://jsrocks.org/images/thumb.png) |

**Comment by UltCombo** [comment]
Nice!
I'm wondering whether we should add a gruntfile to [harmonic-theme-jsrocks](https://github.com/JSRocksHQ/harmonic-theme-jsrocks).
The CSS will soon be generated using Stylus, so I guess we can just enable Stylus output compressing in Harmonic.
The images could be PR'd directly to harmonic-theme-jsrocks.
cc @jaydson @robsongajunior

**Comment by ftonato** [comment]
I think it's a good idea!

**Comment by morvanabonin** [comment]
I like the idea about grunt or gulp to harmonic-theme-jsrocks.

**Comment by ftonato** [comment]
@morvanabonin  +1

**Comment by robsongajunior** [comment]
> The CSS will soon be generated using Stylus, so I guess we can just enable Stylus output compressing in Harmonic.

I see no sense because we will have build logic in back end and front end. I think just one need be responsible for this.

**Comment by robsongajunior** [comment]
by @UltCombo 

> The CSS will soon be generated using Stylus, so I guess we can just enable Stylus output compressing in Harmonic.

I see no sense because we will have build logic in back end and front end. I think just one need be responsible for this.

Grunt/Gulp or implement this enhancement in Harmonic?

**Comment by UltCombo** [comment]
@robsongajunior We're planning to move preprocessing to Harmonic plugins, but the plugin architecture is not implemented yet. Putting it in the core would be a temporary solution.
A task runner could be a better solution in the long run, but that also means one extra build step in each build/deploy.

**Comment by jaydson** [comment]
Some people suggest me this:
`harmonic init` can also have a runner option (Grunt, Gulp, whatever).
So the generated website can have it's own runner.
It seems like a good approach, so we can even start the runner with the `harmonic build` command.

**Comment by UltCombo** [comment]
@jaydson That seems like a good idea at first, but I'm not sure. Let's think about the possible use cases.

The user may want the task runner to be executed before and/or after `harmonic build`. The user may also want to execute specific task(s) before/after `harmonic build`. Providing configuration options for all these cases seem to complicate more than help.

What I mean is, I'm not seeing how those config options would be better than simply running `grunt && harmonic build` or `harmonic build && gulp minify`.

Perhaps we could add `beforeBuild` and `afterBuild` config options to execute user-defined CLI commands before/after the build process.

**Comment by jaydson** [comment]
>  we could add beforeBuild and afterBuild config options to execute user-defined CLI commands

:+1: 

But i agree that simply running both `harmonic` and `grunt/gulp` its kinda easy.

**Comment by UltCombo** [comment]
There are some advantages to having `beforeBuild`/`afterBuild`:

- The user cannot "forget" to run those commands once they're set in the `harmonic.json`, this prevents human errors.
- Once we have watch-build-reload in Harmonic (JSRocksHQ/harmonic#118), the `beforeBuild`/`afterBuild` commands will be seamlessly integrated in the automated build process.

**Comment by ftonato** [comment]
I'm closing outdated issues and pull-requests that are no longer relevant given how much time has passed since they were opened.
