### ISSUE TITLE
Translate article to chinese

### ISSUE THREAD

**Issue by jaydson** [JSRocksHQ/jsrockshq.github.io#62]
Translate new article `how I'm using es6 modules in production` to Chinese.

//cc @hacke2

**Comment by hacke2** [comment]
:ok_hand:I will finish that in this week

**Comment by jaydson** [comment]
Awesome! Thanks @hacke2

**Comment by hacke2** [comment]
finished :kissing:

**Comment by hacke2** [comment]
how do I join JS Rocks organization :question:

**Comment by jaydson** [comment]
You're already a member :)

**Comment by jaydson** [comment]
Done #63

**Comment by UltCombo** [comment]
@hacke2 when we added you to the organization, GitHub sent an email to you to confirm that you really want to be part of the organization. Please check your e-mail.
I'm not sure if China's firewall blocked the email or something else.

**Comment by hacke2** [comment]
The firewall has the world famous...coder use VPN to access Google in china

**Comment by UltCombo** [comment]
Welcome to the org! :smile:
