### ISSUE TITLE
Sharing on Twitter is not working

### ISSUE THREAD

**Issue by ftonato** [JSRocksHQ/jsrockshq.github.io#64]
See image below!

![Example](http://imageshack.com/a/img538/4527/r98KsV.png)

**Comment by jaydson** [comment]
Thanks @ftonato !
Hey @robsongajunior , take a look.

**Comment by UltCombo** [comment]
I made an [emergency fix](https://github.com/JSRocksHQ/harmonic-theme-jsrocks/compare/98150658ba2c275eaa5ebb161ffa112e79dc886e...db9dd32f731568c27dc91f5d7ee69bfe120dd99e), it is now live at <http://jsrocks.org>.
Make sure to hard-refresh the page if you have caching issues.

We would still like to improve those default share texts, see #39

**Comment by jaydson** [comment]
:+1:
