### ISSUE TITLE
Typo in an article

### ISSUE THREAD

**Issue by felipenmoura** [JSRocksHQ/jsrockshq.github.io#65]
In this article, there is a typo in Portuguese: Pŕoximos instead of Próximos
http://jsrocks.org/pt-br/2015/05/how-i-m-using-es6-modules-in-production/

**Comment by UltCombo** [comment]
Nice catch!
@jaydson I wonder how you managed to accentuate an `r`, hahah. :stuck_out_tongue_winking_eye: (joking)

By the way, @felipenmoura you have full access to the repository so you can fix those typos through the GitHub editor interface. Also, I've implemented automatic deploys through Travis CI, so whenever you commit or merge a PR into the `src` branch it will be automatically deployed to the live site.

**Comment by jaydson** [comment]
I'm a Ĺíńúx úśéŕ

**Comment by jcemer** [comment]
+1 for automatically deploy.

**Comment by jaydson** [comment]
Automatically deploy is already working @jcemer

**Comment by jcemer** [comment]
I know! :)

**Comment by jaydson** [comment]
:)

**Comment by felipenmoura** [comment]
ok, gonna do that next time :)
