### ISSUE TITLE
Page "authors" not working

### ISSUE THREAD

**Issue by ftonato** [JSRocksHQ/jsrockshq.github.io#66]
`/authors` don't reference no page!
```
<!-- Humans -->
<link rel="author" href="/AUTHORS" />
```

**Comment by UltCombo** [comment]
Good catch! Please take a look @robsongajunior.
We could link it to [CONTRIBUTORS.md](https://github.com/JSRocksHQ/jsrockshq.github.io/blob/master/CONTRIBUTORS.md), or remove that `<link rel="author">` and use a [humans.txt](http://humanstxt.org/).
/cc @jaydson @felipenmoura

**Comment by UltCombo** [comment]
Or we can have the best of the two worlds, rename `CONTRIBUTORS.md` to `humans.txt` and fix the `rel="author"` to point to it:

```html
<link type="text/plain" rel="author" href="http://jsrocks.org/humans.txt" />
```

**Comment by jaydson** [comment]
:+1: humans.txt

**Comment by robsongajunior** [comment]
Good catch! 

I like what @jaydson has said
> humans.txt

I will take a look.

**Comment by UltCombo** [comment]
@robsongajunior It would be nice if you can follow the recommendations at http://humanstxt.org/

**Comment by UltCombo** [comment]
(Accidental close, oops.)

**Comment by robsongajunior** [comment]
> (Accidental close, oops.)

huaehuhauhuaehuahe

Nice @UltCombo, I will follow __humanstxt__ recomendations.

**Comment by robsongajunior** [comment]
https://github.com/JSRocksHQ/harmonic-theme-jsrocks/pull/32

At harmonic run command, he doesn't copy humans.txt to public paste.
@UltCombo, can you test for us?

**Comment by robsongajunior** [comment]
Fixed

**Comment by UltCombo** [comment]
@robsongajunior you can. :smile:
