### ISSUE TITLE
The categories links are on top of each other, in Other Posts

### ISSUE THREAD

**Issue by ftonato** [JSRocksHQ/jsrockshq.github.io#69]
I opened the post [JavaScript ♥ Unicode](http://jsrocks.org/2014/10/javascript-unicode/) and then I noticed that in the "others posts" section, the categories links were on top of each other, as the following image shows:

![error-01](https://cloud.githubusercontent.com/assets/5417662/10318549/51abb5c8-6c40-11e5-896b-159abdc74665.png)

**Comment by UltCombo** [comment]
Changing `.item-tag-post`'s `margin-top: -8px` to `margin-top: 4px` seems to fix this.

**Comment by Isk1n** [comment]
You should also limit size of short description (div.intro-post), like this http://codepen.io/martinwolf/pen/qlFdp

**Comment by robsongajunior** [comment]
Sorry, today at night, I'll take a look this.

**Comment by Isk1n** [comment]
This http://codepen.io/Isk1n/pen/PPOWMM may help with tags

**Comment by robsongajunior** [comment]
Rebuilding it's needed

**Comment by robsongajunior** [comment]
__Rebuild status__ - Done
http://jsrocks.org/2014/10/javascript-unicode/

Thanks @ftonato
