### ISSUE TITLE
Tutorial on Configuring BabelJS for ES6

### ISSUE THREAD

**Issue by abdulhannanali** [JSRocksHQ/jsrockshq.github.io#71]
Hi! I have written a tutorial about configuring BabelJS for ES6. It's an article I have written as a task for Google CodeIn contest I am participating in. I will be very happy and it'll give me a motivation boost if JSRocks post it on it's website. I will be contributing more to JSRocks in the future since it's run by so awesome people. I came to know JSRocks from @UltCombo profile. I will post here the gist of the article if you are accepting the articles on this topic. Thank you! Stay awesome

**Comment by abdulhannanali** [comment]
This is the task I've written it as a part of

**Comment by abdulhannanali** [comment]
@UltCombo I hope you give it a consideration. Please!!! :smile:

**Comment by abdulhannanali** [comment]
@UltCombo You can check out the first draft of this article here https://github.com/abdulhannanali/babel-configuration-tutorial/blob/master/tutorial.md :+1:

**Comment by UltCombo** [comment]
Hello, @abdulhannanali. Your tutorial looks very nice!  :smile:
I'd love to have it posted on JS Rocks. Can you send a pull request? Here's the [general directions](https://github.com/JSRocksHQ/jsrockshq.github.io/tree/master#writing-an-article).

I've noticed one or two issues that need fixing. I believe the command `npm install --save-dev es-2015 stage-0` should be `npm install --save-dev babel-preset-es2015 babel-preset-stage-0`. I'll be happy to do a more throughout review once we have the pull request open.

Thanks for contributing! :smile_cat:

**Comment by abdulhannanali** [comment]
Thank you very much @UltCombo it's Very appreciated. I am working to open a PR right away. I've corrected the said changes. Thanks for pointing them out. :smile:

**Comment by abdulhannanali** [comment]
@UltCombo Thank you for publishing I am closing this now
