### ISSUE TITLE
Profile pictures

### ISSUE THREAD

**Issue by ftonato** [JSRocksHQ/jsrockshq.github.io#74]
We could use the [Gravatar](https://en.gravatar.com/) or native upload like the @felipenmoura [see here](http://jsrocks.org/avatars/felipenmoura.png).

The `error` can be seen in the posts of @jaydson that use an [image of Twitter](https://pbs.twimg.com/profile_images/453720347620032512/UM2nE21c_400x400.jpeg)

See the page breaking in image below:

![breaking](https://cloud.githubusercontent.com/assets/5417662/12149551/62991bf8-b48b-11e5-9866-24d5b8abf04f.png)

**Comment by robsongajunior** [comment]
Yeah, we can use. Do you want open a PR

**Comment by ftonato** [comment]
@robsongajunior Do you suggest I send a PR containing @jaydson's profile image?

**Comment by jaydson** [comment]
Thanks @ftonato.
It was fixed by my last commit.

**Comment by ftonato** [comment]
The same `error` :skull: it happens in the posts of @UltCombo that use [this image](https://pbs.twimg.com/profile_images/490627147963187200/2BiH3pv4.png)

In the below picture
![error](https://cloud.githubusercontent.com/assets/5417662/12302680/95ebeb84-ba0d-11e5-91a4-6d3c21d471d2.png)

**Comment by UltCombo** [comment]
Oh, guess I can change mine to use Gravatar as well.
Thanks for reporting, I'll fix that when I get home.

**Comment by ftonato** [comment]
:+1:

**Comment by UltCombo** [comment]
My author picture was showing correctly here, but in any case, I've just updated it to avoid future breakage—hotlinking from Twitter is not safe, I've switched the picture to Gravatar.

**Comment by ftonato** [comment]
:+1:
