### ISSUE TITLE
Permission to share

### ISSUE THREAD

**Issue by clovisdasilvaneto** [JSRocksHQ/jsrockshq.github.io#77]
I am in the final stages of developing an application that brings together various news related to the front-end world.

I would like to share your posts if you allow me.

Thanks

**Comment by UltCombo** [comment]
That sounds great. :smiley:
By the way, the whole JS Rocks site is licensed under [MIT](https://github.com/JSRocksHQ/jsrockshq.github.io/blob/master/LICENSE.md), so you technically don't need to ask for permission. :smile_cat:

**Comment by clovisdasilvaneto** [comment]
Thank's man :D
