### ISSUE TITLE
Configuring-babel-6-for-node-js link is dead

### ISSUE THREAD

**Issue by c0debreaker** [JSRocksHQ/jsrockshq.github.io#78]
Hi folks,

This link is dead - http://jsrocks.org/2016/01/configuring-babel-6-for-node-js
I can open other post fine.

Thanks!
V1rt

**Comment by UltCombo** [comment]
Hello, thanks for reporting!

Do you mean you cannot access this link? http://jsrocks.org/2016/01/configuring-babel-6-for-node-js

It seems to be working fine from my machine:

![](http://i.imgur.com/ff1NH2D.png)

Maybe try opening the link in incognito/private mode or clear your cache to see if it helps.

**Comment by montogeek** [comment]
It works on my machine too

**Comment by c0debreaker** [comment]
The culprit is my other wifi access point. I have firewall rules that when it sees a string, it will block the connection. I used my other access point and it's good now. Sorry for the wrong info.
