### ISSUE TITLE
jsrocks.org is out

### ISSUE THREAD

**Issue by felipebernardes** [JSRocksHQ/jsrockshq.github.io#79]
I've been GoDaddie'd:
![](http://i.imgur.com/ImIDMV1.png)

**Comment by UltCombo** [comment]
I've reported this to @jaydson a few days ago as well. Looks like the domain has not been renewed.

**Comment by ftonato** [comment]
jsrocks.org has been **discontinued**?


/cc @UltCombo @jaydson

**Comment by UltCombo** [comment]
[JSRocks.org](http://jsrocks.org) has been up and running shortly after this was reported, closing the issue.
